#!/bin/sh

echo "🔍 Checking commit message format..."

npx --no -- commitlint --edit "$1" || status=$?

if [ $status -ne 0 ]; then
  echo ""
  echo "❌ Invalid commit message format."
  echo "💡 Example: feat(WK-123): add login form"
  echo ""
fi

exit $status
